### ISSUE TITLE
base64 embed detection?

### ISSUE THREAD

**Issue by kerryj89** [projectwallace/wallace-cli#101]
It would be nice to have a section list out base64 embeds along with their filesizes.  Thank you for the wonderful app!

**Comment by kerryj89** [comment]
Nevermind, I see you already have it in your enhancements to possibly come: https://github.com/projectwallace/css-analyzer/issues/264

**Comment by bartveneman** [comment]
Still a good idea to keep this issue open, because adding it to the core analyzer doesn't automatically mean I'll remember to put it in the CLI as well.

**Comment by bartveneman** [comment]
Hey @kerryj89, what do you think of adding it like this?

![Screenshot 2023-09-15 at 20 32 04](https://github.com/projectwallace/wallace-cli/assets/1536852/31041094-24a2-4fa2-8272-30bc537bbda7)

**Comment by bartveneman** [comment]
Fixed in V3 #100
