### ISSUE TITLE
Remove built-in css-fetching

### ISSUE THREAD

**Issue by bartveneman** [projectwallace/wallace-cli#97]
The headless CSS fetching mechanism requires a whole lot of dependencies and install time. I think it should be separated so that it would would be two different steps, using [get-css](https://github.com/projectwallace/extract-css-core) or someone just piping a local file into wallace-cli:

```sh
get-css https://www.projectwallace.com > wallace
```

**Comment by drewlustro** [comment]
Yes please.

Not to mention that `puppeteer` is a nightmare dependency to keep functional with all architectures, platforms, etc.

**Comment by drewlustro** [comment]
Need help with this one?

I'm adopting wallace-cli at my org as an experiment. I'd be willing to give this issue a shot, provided wallace works out for us.

**Comment by bartveneman** [comment]
Should be pretty straightforward, so feel free to pick up, but maybe I'll have some time this weekend to have a look.

**Comment by bartveneman** [comment]
@drewlustro I have a WIP branch that's very lightweight and fast, without Puppeteer that you could try out using `npx https://github.com/projectwallace/wallace-cli\#v3 path/to/style.css`

**Comment by drewlustro** [comment]
@bartveneman – Thanks mate. 

I'm headed to Detroit for a music festival tonight, but will take a look next Thursday.

**Comment by mryechkin** [comment]
> @drewlustro I have a WIP branch that's very lightweight and fast, without Puppeteer that you could try out using `npx https://github.com/projectwallace/wallace-cli\#v3 path/to/style.css`

Does this work for anyone else? I just tried running and nothing happens:
![Screenshot 2023-09-06 at 1 17 29 PM](https://github.com/projectwallace/wallace-cli/assets/5657181/1b78dbee-c252-46ec-a5aa-388c6af56e92)

**Comment by bartveneman** [comment]
I had to push some untested local changes because I got a new computer a while back, so its very well possible this branch is currently broken. I completely forgot about it.

Did you hit enter when it asked you to proceed though?

**Comment by mryechkin** [comment]
> Did you hit enter when it asked you to proceed though?

Yes, nothing happened - just returned me to the terminal.

I was able to build the v3 branch locally and use it that way, and it worked great - but obviously that's a temporary solution. Hopefully that PR can get merged at some point.
